import { useEffect, useRef, useState } from "react";
import Loader from "./Loader";

const FAKE_DETECTIONS = [
  { label: "Spines", ctx: "Shelf", conf: "High" },
  { label: "Covers", ctx: "Stack", conf: "Medium" },
  { label: "Pages", ctx: "Open book", conf: "Low" },
  { label: "Mixed", ctx: "Handheld", conf: "Medium" },
];

const Status = () => {
  const [open, setOpen] = useState(false);
  const [liveStatus, setLiveStatus] = useState("Initializing scanner…");
  const [history, setHistory] = useState([]);

useEffect(() => {
  let intervalId;

  // Phase 1: startup message
  setLiveStatus("Loading scanner…");

  const startScanning = () => {
    const tick = () => {
      const d =
        FAKE_DETECTIONS[Math.floor(Math.random() * FAKE_DETECTIONS.length)];

      const msg = `Detecting: ${d.label} · ${d.ctx} (${d.conf})`;

      setLiveStatus(msg);

      const time = new Date().toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
      });

      setHistory((h) => [{ time, msg }, ...h].slice(0, 8));
    };

    tick(); // immediate first detection
    intervalId = setInterval(tick, 2000);
  };

  // Phase 2: start real scanning after 4s
  const startupTimeout = setTimeout(startScanning, 4000);

  return () => {
    clearTimeout(startupTimeout);
    clearInterval(intervalId);
  };
}, []);


  return (
    <>
     {/* EXPANDED SHEET (DIALOG BOUNDARY) */}
<dialog
  open={open}
  className="
    fixed inset-0
    bg-transparent
    p-0 m-0
    max-w-none
  "
>
  {/* SCRIM — CLICK OUTSIDE */}
  <div
    className="absolute inset-0"
    onClick={() => setOpen(false)}
  />

  {/* SHEET SURFACE */}
  <div
    className="
      fixed left-4 right-4
      bottom-[3.5rem]
      max-h-[70vh]
      bg-black/30 backdrop-blur
      rounded
      shadow-lg
      overflow-hidden
      transition-all duration-200 ease-out
      pointer-events-auto
    "
  >
    <div className="p-4 space-y-4 text-sm overflow-y-auto max-h-[70vh]">
      <div className="flex items-center justify-between">
        <div className="font-semibold text-gray-100">
          Scanner status
        </div>
        <button
          onClick={() => setOpen(false)}
          className="text-gray-200 hover:text-gray-100"
        >
          ✕
        </button>
      </div>

      <div>
        <div className="font-medium mb-1 text-gray-100">
          Live detection
        </div>
        <div className="text-xs text-gray-400">
          {liveStatus}
        </div>
      </div>

      <div>
        <div className="font-medium mb-1 text-gray-100">
          Detection history
        </div>
        <ul className="text-xs text-gray-400 space-y-1">
          {history.map((h, i) => (
            <li key={i}>
              {h.time} — {h.msg}
            </li>
          ))}
        </ul>
      </div>

      <div className="text-xs text-gray-400 pt-2">
        Status updates are generated by the scan engine in real time.
      </div>
    </div>
  </div>
</dialog>


      {/* STATUS BAR (collapsed state) */}
      <footer
        onClick={() => setOpen((o) => !o)}
        className="
    fixed bottom-0 left-0 right-0
  bg-black/30 backdrop-blur
    m-4
    px-4 py-2
    rounded
    text-xs text-gray-100
    flex items-center justify-between
    cursor-pointer
    select-none
  "
      >
        <span className="flex gap-2 items-center">
          <Loader /> {liveStatus}{" "}
        </span>
        <span
          className={`transition-transform text-gray-200 ${
            open ? "rotate-180" : ""
          }`}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="18"
            height="18"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="lucide lucide-chevron-up-icon lucide-chevron-up"
          >
            <path d="m18 15-6-6-6 6" />
          </svg>
        </span>
      </footer>
    </>
  );
};

export default Status;
